title: Thompson Artwork
tagline: Creative sanctuary for medical illustrator Molly Thompson.
# email: your-email@example.com
author: Molly Thompson
logo: # URL to a site-wide logo
description: >- # this means to ignore newlines until "baseurl:"
  Molly Thompson is a board certified medical illustrator who makes recreational art in her free time. Her personal work counterbalances the demands of her profession, offering a sanctuary for creative studies and emotional expression.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thompsonartwork.com"

## Jekyll-SEO-Tag specific
twitter:
  card: photo

# social: 
#   name: {{ author }}
#   links:
#     - https://twitter.com/MollyThompson
#     - https://www.facebook.com/MollyThompson

# google_site_verification:

## Dev only setting
host: 0.0.0.0

show_excerpts: true

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  # archives:
  #   output: true
  #   permalink: /archives/:path/
  drawings:
    title: Drawings
    weight: 1
    output: true
    permalink: /galleries/:collection/:path/
  studies:
    title: Studies
    weight: 2
    output: true
    permalink: /galleries/:collection/:path/
  digital-art:
    title: Digital Art
    weight: 3
    output: true
    permalink: /galleries/:collection/:path/
  kid-stuff:
    title: Kid Stuff
    weight: 4
    output: true
    permalink: /galleries/:collection/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - makefile
  - update_bootstrap.sh
