title: Thompson Artwork
# email: your-email@example.com
author: Molly Thompson
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thompsonartwork.com" # the base hostname & protocol for your site, e.g. http://example.com

## Dev only setting
host: 0.0.0.0

show_excerpts: true

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag ## NOT TESTED

# tags:
#   featured:
#     output: true

collections:
  drawings:
    title: Drawings
    output: true
    permalink: /galleries/:collection/:path/
  studies:
    title: Studies
    output: true
    permalink: /galleries/:collection/:path/
  digital-art:
    title: Digital Art
    output: true
    permalink: /galleries/:collection/:path/
  kid-stuff:
    title: Kid Stuff
    output: true
    permalink: /galleries/:collection/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - makefile
  - update_bootstrap.sh
