backend:
  name: github
  repo: lyonritchie/thompsonartwork
  branch: master
  site_domain: practical-shannon-ea7423.netlify.app

media_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'post'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        required: true
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO'
        required: false
      - label: 'Keywords'
        name: 'keywords'
        widget: 'string'
        hint: 'SEO'
        required: false
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: false

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - name: 'about'
        label: 'About/Contact'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'About/Contact' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/about/' }
          - { label: 'Order', name: 'order', widget: 'number', valueType: 'int', default: '2' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'shop'
        label: 'Shop'
        file: 'shop.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Shop Links' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/shop/' }
          - { label: 'Order', name: 'order', widget: 'number', valueType: 'int', default: '4' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'galleries'
        label: 'Galleries'
        file: 'galleries.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Galleries Links' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/galleries/' }
          - { label: 'Order', name: 'order', widget: 'number', valueType: 'int', default: '1' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  
  - name: 'digital-art'
    label: 'Digital Art'
    folder: '_digital-art/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Keywords'
        name: 'keywords'
        widget: 'string'
        hint: 'SEO'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/digital-art'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false

  - name: 'drawings'
    label: 'Drawings'
    folder: '_drawings/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Keywords'
        name: 'keywords'
        widget: 'string'
        hint: 'SEO'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/drawings'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false
      
  - name: 'kid-stuff'
    label: 'Kid Stuff'
    folder: '_kid-stuff/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Keywords'
        name: 'keywords'
        widget: 'string'
        hint: 'SEO'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/kid-stuff'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false

  - name: 'studies'
    label: 'Studies'
    folder: '_studies/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Keywords'
        name: 'keywords'
        widget: 'string'
        hint: 'SEO'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/studies'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false