backend:
  name: github
  repo: lyonritchie/thompsonartwork
  branch: master
  site_domain: practical-shannon-ea7423.netlify.app

media_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'post'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        required: true
      - label: 'Image Thumbnail'
        name: 'image_tn'
        widget: 'image'
        media_folder: '/uploads/thumbnail'
        config:
          - multiple: false
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO: Will be used in the site meta-description tag.'
        required: false
      - label: 'Topics'
        name: 'tags'
        widget: 'list'
        hint: 'Be sure to match the topic name used in Topics.'
        required: false

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - name: 'home'
        label: 'Home'
        file: 'index.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Content will appear at the top of the page.', required: false }
          - { label: 'Description', name: 'description', widget: 'text', hint: 'SEO: Will be used in the site meta-description tag. Note: This will override the description already set in the site config.', required: false }
      - name: 'about'
        label: 'About/Contact'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'About/Contact' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/about/' }
          - { label: 'Order', hint: 'Location within main navigation.', name: 'order', widget: 'number', valueType: 'int', default: '2' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Description', name: 'description', widget: 'text', hint: 'SEO: Will be used in the site meta-description tag.', required: false }
      - name: 'shop'
        label: 'Shop'
        file: 'shop.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Shop Links' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/shop/' }
          - { label: 'Order', hint: 'Location within main navigation.', name: 'order', widget: 'number', valueType: 'int', default: '4' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
          - { label: 'Description', name: 'description', widget: 'text', hint: 'SEO: Will be used in the site meta-description tag.', required: false }
          - { label: 'Published', name: 'published', widget: 'boolean' }
      - name: 'galleries'
        label: 'Galleries'
        file: 'galleries.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Galleries Links' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'permalink', name: 'permalink', widget: 'hidden', default: '/galleries/' }
          - { label: 'Order', hint: 'Location within main navigation.', name: 'order', widget: 'number', valueType: 'int', default: '1' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
          - { label: 'Description', name: 'description', widget: 'text', hint: 'SEO: Will be used in the site meta-description tag.', required: false }
  
  - name: 'digital-art'
    label: 'Digital Art'
    folder: '_digital-art/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/digital-art'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        hint: 'Affects sort order in gallery.'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        options: ["cover", "featured"]
        multiple: true
        hint: 'Show image on home page (featured) or as the gallery cover image.'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false

  - name: 'drawings'
    label: 'Drawings'
    folder: '_drawings/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/drawings'
        config:
          - multiple: false
      - label: 'Image Thumbnail'
        name: 'image_tn'
        widget: 'image'
        media_folder: '/uploads/drawings/thumbnail'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        hint: 'Affects sort order in gallery.'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        options: ["cover", "featured"]
        multiple: true
        hint: 'Show image on home page (featured) or as the gallery cover image.'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false
      
  - name: 'kid-stuff'
    label: 'Kid Stuff'
    folder: '_kid-stuff/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/kid-stuff'
        config:
          - multiple: false
      - label: 'Image Thumbnail'
        name: 'image_tn'
        widget: 'image'
        media_folder: '/uploads/kid-stuff/thumbnail'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        hint: 'Affects sort order in gallery.'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        options: ["cover", "featured"]
        multiple: true
        hint: 'Show image on home page (featured) or as the gallery cover image.'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false

  - name: 'studies'
    label: 'Studies'
    folder: '_studies/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'galleryitem'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
        hint: 'SEO + Social Sharing'
        required: false
      - label: 'Image'
        name: 'image'
        widget: 'image'
        media_folder: '/uploads/studies'
        config:
          - multiple: false
      - label: 'Image Thumbnail'
        name: 'image_tn'
        widget: 'image'
        media_folder: '/uploads/studies/thumbnail'
        config:
          - multiple: false
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:MM:SS ZZ'
        default: ''
        hint: 'Affects sort order in gallery.'
        required: true
      - label: 'Tags'
        name: 'tags'
        widget: 'select'
        options: ["cover", "featured"]
        multiple: true
        hint: 'Show image on home page (featured) or as the gallery cover image.'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false

  - name: 'archives'
    label: 'Archives'
    folder: '_archives/'
    create: true
    slug: '{{fields.topic}}'
    editor:
      preview: false
    fields:
      - label: 'Year'
        name: 'topic'
        widget: 'string'
        hint: 'Year in YYYY format'
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false

  - name: 'topics'
    label: 'Topics'
    folder: '_topics/'
    create: true
    slug: '{{fields.topic}}'
    editor:
      preview: false
    fields:
      # - label: 'Topic Title'
      #   name: 'title'
      #   widget: 'string'
      #   hint: 'If not rendered properly from Topic, enter what you would like as a title for the topic page.'
      #   required: false
      - label: 'Topic'
        name: 'topic'
        widget: 'string'
        hint: 'Topic name in lowercase. No spaces or special characters, except dash.'
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false